content/docs/getting-started/fluvio-local-faq.md
content/docs/getting-started/fluvio-local.md

As of infinyon/fluvio#358, users no longer need to do two install commands (one with `--sys` and one without). As of some earlier point in time, they also do not need to manually pass `--chart-version` and `--image-version`. I've updated the documentation to reflect these changes.

Update docs with install printout to match updated CLI

---

assets/styles/_highlight.scss
content/docs/getting-started/fluvio-cli.md
content/docs/getting-started/fluvio-cloud.md

Now that we have the one-liner install script, I wanted to update the CLI docs to reflect it.

Add new CLI installation instructions to docs

---

content/docs/getting-started/fluvio-local.md

There was confusion before about whether the Fluvio CLI was needed for a local installation because the wording on the Prerequisite section seemed to indicate that the CLI was for Fluvio Cloud only. This updates the wording to make it more clear.

Fix wording on fluvio-local prerequisites

---

content/docs/getting-started/fluvio-local.md

The old minikube tunnel command would cause the terminal to hang. This is a version of the command that will not hangup, and it will also not get stuck on sudo because we make sure to prompt sudo before backgrounding the process.

Update minikube tunnel command

---

content/tutorials/node/hello-world.md
content/tutorials/rust/hello-world.md

Our tutorials do not work with certain outdated Fluvio versions. I have added minimum Fluvio version numbers to the tutorials to prevent future users from encountering the same trouble that has been seen before https://github.com/infinyon/fluvio/issues/660#issuecomment-758025652

Add minimum version numbers and update instructions to tutorials

---

content/docs/fluvio-cloud/release-notes.md

This moves the `release-notes` page under the Fluvio Cloud section

Move release notes into fluvio-cloud

---

content/blog/_posts/2021-02-fluvio-cloud.md

I think I spent more time thinking about what we should write than actually writing. I settled on a simple tutorial that's basically the same thing as running fluvio. The point behind doing it here is that it highlights the core value proposition of fluvio cloud - Building a streaming data app without the hassle of devops.
Our first version of this just had too much "About Fluvio" and not enough "about fluvio cloud". We don't have enough features yet to have something like [the EKS AWS announcment](https://aws.amazon.com/blogs/aws/amazon-eks-now-generally-available/) but we will eventually. So, in our case, it's a bit more terminal stuff than graphics of the website.
It's not quite the same but this is what the post looks like [rendered](https://github.com/simlay/fluvio-website/blob/cloud- …

Cloud announcment rewrite

---

assets/styles/_highlight.scss

This gives code blocks a soft raised look that I really like. It basically rounds them and raises them a bit using shadows

Add border-rounding and shadow to code blocks

---

content/cli/_index.md

The only CLI command we have that references SmartStreams right now is `fluvio consume --smart-stream=...` so I inflated this section in the overview with various links to other parts of the documentation for SmartStreams. In the future I expect we will have more CLI-oriented links to put here but I like this for now.

Add a SmartStream section to the CLI reference

---

content/docs/smartstreams/api.md

I believe this API was changed after upgrading to 0.9. This PR should fix the example.

Update filter example to use with v0.9.x

---

content/connectors/_index.md
content/connectors/sources/http.md
content/connectors/sources/mqtt.md

After a last run-through, I spotted a few places where we needed updates. With these changes, following the whole doc using copy/paste works as expected.

Update smartstream to smartmodule. Fix docker commands

---

content/_index.md
content/cli/_index.md
content/cli/commands/consume.md
content/connectors/_index.md
content/docs/_index.md
content/docs/smartmodules/_index.md
content/docs/smartmodules/aggregate.md
content/docs/smartmodules/api.md
content/docs/smartmodules/array-map.md
content/docs/smartmodules/filter.md
content/docs/smartmodules/map.md
content/docs/smartmodules/quick-start.md
content/news/this-week-in-fluvio-0011.md
netlify.toml

This PR changes all references of `SmartStream` to `SmartModule` following the recent renaming. There should no longer be any reference to "SmartStream" except for within URLs to the InfinyOn site.

Update `SmartStream` to `SmartModule` in docs

---

content/docs/get-started/mac_m1.md

Adjust the recommend kind configuration to map the correct node ports based on the defaults set in the Helm Chart for the fluvio install.
closes #259

fix recommended kind config for mac m1 getting started docs 

---

content/cli/commands/connector.md
content/connectors/_index.md
content/connectors/examples/github.md
content/connectors/sinks/postgres.md
content/connectors/sources/http.md
content/connectors/sources/mqtt.md
content/connectors/sources/postgres.md
content/connectors/sources/template.md
content/news/this-week-in-fluvio-0009.md
content/news/this-week-in-fluvio-0010.md
content/news/this-week-in-fluvio-0014.md
content/news/this-week-in-fluvio-0020.md
content/news/this-week-in-fluvio-0022.md

Removes the deprecated create_topic (https://github.com/infinyon/fluvio/issues/2200)
Merge to stable when 0.9.20 is released

Deprecate connectors create topic

---

content/connectors/_index.md
content/connectors/examples/github.md
content/connectors/sources/http.md
content/connectors/sources/mqtt.md
content/connectors/sources/postgres.md
content/connectors/sources/template.md
content/news/this-week-in-fluvio-0009.md
content/news/this-week-in-fluvio-0010.md
content/news/this-week-in-fluvio-0014.md
content/news/this-week-in-fluvio-0022.md

* Aligns and pins the connector versions to current or future current 0.2.0 in case of mqtt
* Also I took the liberty to fix `fluvio smartmodule` to be `fluvio smart-module` in the github example
* Can be pushed to stable after mqtt connector 0.2.0 out

fix(connectors): align and pin versions to current

---

content/connectors/examples/github.md

Hi!
I was following along the tutorial and found an error:
```
➜  github-stars git:(master) ✗ fluvio smartmodule create github-smartmodule --wasm-file=target/wasm32-unknown-unknown/release/github_stars.wasm
Unable to find plugin 'fluvio-smartmodule'. Make sure it is installed in "/home/stefano/.fluvio/extensions".
```
There is a dash missing in the command. See pull request.
Version info & output with dash:
```
➜  github-stars git:(master) ✗ fluvio smart-module create github-smartmodule --wasm-file=target/wasm32-unknown-unknown/release/github_stars.wasm
➜  github-stars git:(master) ✗ fluvio smart-module list
NAME                STATUS             SIZE 
github-smartmodule  SmartModuleStatus  140785 
➜  github-stars git:(master) ✗ fluvio version  
Release Channel      : stable
Fluvio CLI …
```

Fix github stars example commands

---

content/cli/advanced/consume_table.md
content/cli/commands/consume.md
content/cli/commands/table-format.md
content/news/this-week-in-fluvio-0015.md
content/news/this-week-in-fluvio-0017.md

With the change to clap in https://github.com/infinyon/fluvio/pull/2281 full_table was changed to full-table: See https://github.com/clap-rs/clap/issues/3564
This PR changes all occurrences of `full_table` with `full-table`

's/full_table/full-table/g'

---

content/connectors/_index.md

Fix typo: connectors -> _index.md

---

content/news/this-week-in-fluvio-0046.md

Just another deprecation warning. But this time I've got a link to the in-progress migration tool, for other Rust developers to look at until we get it documented.

Add This week in Fluvio 46

---

content/cli/advanced/cli_channels.md
embeds/download-cli/curl-bash-copy.md

change hub-dev to hub (hub-dev changed the fvm endpoint in prep for next release)

fixup docs before fvm release

---

content/connectors/cdk/build-test.md
content/connectors/cdk/start-shutdown.md
embeds/cdk/tree-output.md
embeds/cli/example/cdk-generate-example.md
embeds/connectors/inbound/http.md
embeds/connectors/inbound/kafka.md
embeds/connectors/inbound/mqtt.md
embeds/connectors/outbound/http.md
embeds/connectors/outbound/kafka.md

that's the name of the file generated by `cdk generate`
```
❯ ls -l
total 108
-rw-r--r-- 1 m m 86529 Dec 21 23:05 Cargo.lock
-rw-r--r-- 1 m m   445 Dec 21 23:03 Cargo.toml
-rw-r--r-- 1 m m   287 Dec 21 23:03 Connector.toml
-rw-r--r-- 1 m m    24 Dec 21 23:03 .gitignore
-rw-r--r-- 1 m m     6 Dec 21 23:03 README.md
-rw-r--r-- 1 m m   133 Dec 21 23:03 sample-config.yaml
drwxr-xr-x 1 m m    32 Dec 21 23:03 src
drwxr-xr-x 1 m m   120 Dec 21 23:05 target
```
i blindly renamed every occurrence, don't approve without careful review, as i havent made myself familiar with all docs yet
```
❯ fluvio version
Fluvio CLI           : 0.11.2
Fluvio CLI Arch      : x86_64-unknown-linux-musl
Fluvio CLI SHA256    : ad780eb2573279ad625ddc373fea8701a3d3478763e1af99d365c5903ef24006
Fluvio channel frontend …
```

docs: change `config-example.yaml` to `sample-config.yaml`

---

content/docs/concepts/topics.md

I thought it might be useful to others to have "SPU" spelled out the first time it's mentioned, with a link to the SPU page in the Architecture section. This could trip people up if they're going through the docs in order, since SPU isn't explained until a later section.

Clarified the term SPU and linked to appropriate page

---

.github/workflows/htmltest.yml

merge to stable blocked because lint does not run on pr

chore: fix lint ci

---

content/docs/install.md

modify fish script to include ~/.fvm/bin directory

fix: fish script missing .fvm/ dir

---

content/news/this-week-in-fluvio-0058.md
content/news/this-week-in-fluvio-0059.md

- **Fluvio newsletter update 03-06 (#809)**
- **update Fluvio newsletter issue 59 (#811)**

sync master to stable 2024 03 06 ac
