- content/docs/cli/_index.md
I have updated the code and relevant documentation in fluvio as well.
> Updated latest CLI documentation

- content/docs/architecture/_index.md
@ajhunyady here's the updated Topics and Partitions section. I noticed there's an image nearby, we may want to update that to represent the example we're going with.
> Update Topics and Partitions section

- content/docs/architecture/client.md
changed from home grown to purpose built.
> minor change in wording

- .gitignore
- content/docs/_index.md
Biggest content difference is updating the "Speed" bullet points. I added references to "Fearless Concurrency" and "Why Async" from the rust ecosystem, which are great explanations of the value of those things.
> Add links and update formatting for docs homepage

- WRITERS.md
Is there a way to preview the rendered site before merging?
> Fix .github filename

- assets/styles/_callout.scss
- assets/styles/_params.scss
- content/docs/cli/_index.md
- content/docs/getting-started/_index.md
- content/docs/getting-started/fluvio-cli.md
- content/docs/getting-started/fluvio-cloud.md
- content/docs/getting-started/fluvio-local-faq.md
- content/docs/getting-started/fluvio-local.md
- content/docs/getting-started/install-local.md
- content/docs/kubernetes/_index.md
I'm working on writing the getting-started pages to be suitable for a brand new user. I'm hoping this will be complete enough to guide users who have never used Kubernetes or Minikube before. Feeback is welcome!
> Begin rewriting getting-started/overview page

- content/docs/architecture/client.md
- content/tutorials/hello-world-node.md
- content/tutorials/hello-world-rust.md
- content/tutorials/hello-world-swift.md
- content/tutorials/hello-world.md
Updates to the `Hello, World!` example for node client.
> Updates to Node.js tutorial and hello, world demo

- content/docs/getting-started/fluvio-local.md
> Set Prerequisites to H2

- content/docs/getting-started/fluvio-cloud.md
> Adjust alignment and sizing of images on Cloud docs

- content/docs/getting-started/fluvio-cli.md
> Update Fluvio CLI install instructions

- content/docs/fluvio-cloud/_index.md
- content/docs/getting-started/fluvio-cloud.md
> add node to sign up for Fluvio Cloud

- content/tutorials/node/hello-world.md
- content/tutorials/rust/hello-world.md
This fixes some problems in the code, and also splits the producer and consumer into two separate functions
> Update Rust hello world

- content/docs/getting-started/fluvio-cli.md
- content/docs/getting-started/fluvio-local-faq.md
- content/docs/getting-started/fluvio-local.md
This updates the getting started page to match the latest commands and version numbers necessary. I have also verified that these steps work from top to bottom to get a new Fluvio setup up and running.
> Update getting started

- content/docs/release-notes.md
Adds a Fluvio Cloud changelog to the website.
> Add initial changelog

- content/tutorials/rust/hello-world.md
- layouts/partials/main/code/rust-consumer.md
Got changes for the fluvio-demo-app-rust repo but I want to push the rust client 0.5 to crate.io first.
> Updated for new rust client

- content/docs/fluvio-cloud/release-notes.md
- content/docs/getting-started/_index.md
- content/docs/getting-started/fluvio-cloud.md
- content/docs/getting-started/fluvio-local.md
- content/tutorials/rust/hello-world.md
- Updates documentation with up-to-date CLI output and versions
- Updates Fluvio Cloud release notes
> Update for release

- content/docs/cli-reference.md
- Closes infinyon/fluvio#835
- Closes infinyon/fluvio#833
> Add reference documentation for fluvio-cloud-login and fluvio-cluster-spu-list

- content/tutorials/node/hello-world.md
- content/tutorials/rust/hello-world.md
- layouts/partials/main/code/node-consumer.md
- layouts/partials/main/code/node-producer.md
- layouts/partials/main/code/rust-consumer.md
- layouts/partials/main/code/rust-producer.md
The only reason this is in draft mode is that I need to check that the code changes I made here can be copy-pasted and still work. I tend to update it by hand first and then go back and test it.
> Update code snippets on front page and tutorials

- content/blog/_posts/2021-03-key-value.md
This is a first draft of a blog post for the new key/value feature. This is still a bit of a work in progress because the CLI interface for key/value is still in review. The rest of the content is ready for some quick proofreading though, and feedback is welcome!
> Key value blog

- config.toml
- content/tutorials/python/hello-world.md
- layouts/partials/main/code-samples.html
- layouts/partials/main/code/python-consumer.md
- layouts/partials/main/code/python-producer.md
Depends on https://github.com/infinyon/fluvio-client-python/pull/13.
> Python updates

- content/blog/_posts/2021-04-batch-producer.md
[Rendered](https://github.com/infinyon/fluvio-website/blob/produce-batch-node-tuples-blog/content/blog/_posts/2021-04-batch-producer.md)
> First draft of batch producer blog

- content/docs/getting-started/_index.md
- content/tutorials/rust/hello-world.md
- Updates getting started code snippets
- Updates dependency versions in Rust tutorial
> Update docs and tutorials for 0.8.0 release

- assets/styles/_highlight.scss
- content/cli/advanced/runner.md
- content/cli/commands/cluster.md
- content/cli/commands/consume.md
- content/cli/commands/install.md
- content/cli/commands/partition.md
- content/cli/commands/produce.md
- content/cli/commands/profile.md
- content/cli/commands/topic.md
- content/cli/commands/update.md
- content/cli/commands/version.md
- content/cli/modules/cloud.md
- content/cli/plugins/_index.md
- content/cli/plugins/cloud.md
This supersedes #84 now that the new site has been merged.
> Add CLI reference documentation to new site

- content/docs/_index.md
> fixed java badge link

- content/download/_index.md
- layouts/partials/download/download.html
- layouts/shortcodes/download-card.html
* Update download template
* Add shortcode for styling that used to be in template
* Use content in Download page
* Add a next-steps section to link to get started
* Specify MacOS/Linux in both download and next steps
> Update download page

- content/_index.md
- content/docs/smartstreams/quick-start.md
Reverts infinyon/fluvio-website#123
> Revert "Add WebAssembly name to homepage jumbotron. Link to WASM from quickstart"

- content/_index.md
- content/cli/commands/consume.md
- content/cli/commands/produce.md
- content/docs/architecture/topic-partitions.md
Add section to Architecture > Topics/Partitions about the behavior of producers and consumers with multiple partitions.
- Adds detailed docs and examples for producer with multiple partitions
- Adds more doc and examples for consumer with multiple partitions
> Add behavior docs for producer. Start for consumer

- content/cli/commands/produce.md
Acompanies infinyon/fluvio#1148
- Adds reference documentation for `fluvio produce --raw`
> Update fluvio produce reference with --raw flag

- content/docs/get-started/mac.md
Part of 0.9.0 checklist
>  Review the "getting started" docs on fluvio.io/docs
> Update MacOS getting started for local cluster

- content/api/fluvio/java.md
- content/api/fluvio/node.md
- content/api/fluvio/python.md
- content/api/fluvio/rust.md
Update all codeblocks to have copy
> Update python examples

- content/docs/smartstreams/map.md
Closes https://github.com/infinyon/fluvio-website/issues/135
> Minimal SmartStream Map docs

- content/news/this-week-in-fluvio-0002.md
* this-week-in-fluvio 2
* Add SPU blurb
> Merge this-week-in-fluvio 2 (#153) to stable

- content/cli/commands/cluster.md
- content/cli/commands/consume.md
- content/cli/commands/produce.md
- content/cli/commands/profile.md
- content/cli/plugins/cloud.md
- content/docs/smartstreams/filter.md
A few inconsistencies I've found while going through the docs.
ty.
> Fix small issues in cli docs

- content/news/this-week-in-fluvio-0011.md
This post was lacking a bit with code and cli examples to look at.
> Update twif 11 w/ examples

- content/cli/commands/completion.md
Adding a completion.md for a more in depth explanation of adding fluvio completions to one's .bashrc file
This PR is the "second half" of issue #1850 in the fluvio repo.
A list of issues closed by or relevant to this PR.
- Closes [#215 ] (https://github.com/infinyon/fluvio-website/issues/215).
> Update docs to walkthrough completions

- content/news/this-week-in-fluvio-0015.md
Forgot to push before the previous PR was merged. This will match the content up to the screenshot from #213
> TWiF 15 complete

- assets/styles/_tabs.scss
- assets/styles/fluvio.scss
- content/connectors/examples/_index.md
- content/connectors/examples/github.md
- content/connectors/examples/overview.md
First pass of an end-to-end SmartModule example for Smart Connectors, featuring a GitHub Stars use-case
Rendered
> GitHub example

- content/cli/advanced/consume_table.md
- content/cli/commands/table-format.md
Resolves #198 
(Screenshot from Dec 9)
> Table display related docs

- content/news/this-week-in-fluvio-0016.md
> Add This week in Fluvio 16

- content/news/this-week-in-fluvio-0017.md
> Add This week in Fluvio 17

- content/news/this-week-in-fluvio-0018.md
> This week in Fluvio 18

- content/news/this-week-in-fluvio-0018.md
> Update TWIF 18 - Add consume to end and connectors examples

- content/news/this-week-in-fluvio-0018.md
> Remove mention of 3rd party connectors

- content/news/this-week-in-fluvio-0019.md
> This week in Fluvio 19

- content/_index.md
- content/news/this-week-in-fluvio-0020.md
> This week in Fluvio 20

- content/news/this-week-in-fluvio-0020.md
Mention creating topic manually
> TWiF 20 - Add links to tools

- content/connectors/sources/http.md
Documents http full feature:
- [fluvio-connectors/pull/127](https://github.com/infinyon/fluvio-connectors/pull/127)
- [fluvio-connectors/issues/97](https://github.com/infinyon/fluvio-connectors/issues/97)
> feat: http full

- content/news/this-week-in-fluvio-0021.md
> This week in Fluvio 21

- content/api/_index.md
- content/api/fluvio/rust.md
- content/docs/clients/producer.md
> Update fluvio.io producer documentation

- content/connectors/sources/http.md
> feat(connectors): http json

- content/connectors/sources/postgres.md
- content/news/this-week-in-fluvio-0021.md
- content/news/this-week-in-fluvio-0022.md
> This week in Fluvio 22

- content/api/_index.md
- content/news/this-week-in-fluvio-0023.md
- hugo-start.sh
> This week in Fluvio 23

- content/news/this-week-in-fluvio-0023.md
> docs: http version pin

- content/docs/operations/retention.md
- content/news/this-week-in-fluvio-0022.md
- content/news/this-week-in-fluvio-0024.md
Might need to split off retention docs, but it is referenced in 24
TWiF 24:
Retention docs: (Resolves #243)
> Docs for retention + TWiF 24

- content/_index.md
- content/cli/commands/produce.md
- content/connectors/developer-guide/development-workflow.md
- content/connectors/sources/postgres.md
- content/docs/operations/troubleshoot.md
- content/news/this-week-in-fluvio-0000.md.tmpl
- content/news/this-week-in-fluvio-0025.md
> Twif 25 v2

- content/news/this-week-in-fluvio-0000.md.tmpl
- content/news/this-week-in-fluvio-0027.md
> This week in Fluvio 27

- content/docs/architecture/overview.md
- content/docs/operations/retention.md
Added documentation for recently introduced feature infinyon/fluvio#2179
Closes infinyon/fluvio#2179
> Add `Max Partition Size` docs

- content/docs/operations/retention.md
- content/news/this-week-in-fluvio-0029.md
Added an entry to the upcoming newsletter and a couple of minor changes Data Retention section.
> Add `Max Partition Size` feature note to the newsletter

- content/cli/commands/topic.md
> Add compression-type to topic create

- content/news/this-week-in-fluvio-0030.md
> This week in Fluvio 30

- content/news/this-week-in-fluvio-0030.md
* This week in Fluvio 30
Moving content from 29 into this release
* Add new release link
I expect that we're releasing this week
* This week in Fluvio 30
* Update feature : profile export description
per feedback
* Add blog posts
> This week in Fluvio 30 (#303)

- content/news/this-week-in-fluvio-0031.md
> Add This week in Fluvio 31

- content/news/this-week-in-fluvio-0000.md.tmpl
- content/news/this-week-in-fluvio-0029.md
- content/news/this-week-in-fluvio-0030.md
- content/news/this-week-in-fluvio-0031.md
- content/news/this-week-in-fluvio-0032.md
> This week in Fluvio 32

- content/news/this-week-in-fluvio-0000.md.tmpl
- content/news/this-week-in-fluvio-0034.md
> Add This week in Fluvio 34

- content/news/this-week-in-fluvio-0035.md
> Add This week in Fluvio 35

- content/smartmodules/_index.md
Some re-writes to sections, fixing links, formatting
Fixes #323
> Overhaul SmartModules page

- content/connectors/sinks/kafka.md
- content/connectors/sources/kafka.md
This is pretty bare bones right now. We will eventually want more.
> Initial kafka source and sink docs

- content/connectors/_index.md
I did a lot of this with `jq` so this should be automated in the future.
> Added Simple common arguments for connectors

- content/news/this-week-in-fluvio-0000.md.tmpl
- content/news/this-week-in-fluvio-0036.md
> Add This week in Fluvio 36

- .github/workflows/check_examples.yml
- content/docs/clients/producer.md
> Add section about Producer configs

- content/connectors/_index.md
- content/connectors/sinks/kafka.md
- content/connectors/sinks/postgres.md
- content/connectors/sources/http.md
- content/connectors/sources/mqtt.md
- content/connectors/sources/postgres.md
Updates the docs for the newest stuff for fluvio and fluvio-connectors.
> Update docs for 0.9.28 release

- .github/workflows/check_examples.yml
- .github/workflows/ci.yml
- content/news/this-week-in-fluvio-0000.md.tmpl
- content/news/this-week-in-fluvio-0038.md
- new-twif-post.sh
* This week in fluvio 38
Plus some automation
* Add a CI for the site
Curious if we can use the artifacts for review
* Forgot to give name
* Fix typo in ci yaml
* Update concurrency groups
* reduce retention to 7 days
> Twif 38 (#357)

- content/connectors/_index.md
Subtask of https://github.com/infinyon/fluvio/pull/2464
> Connector describe documentation

- content/connectors/examples/github.md
- content/connectors/sinks/dynamodb.md
- content/connectors/sinks/kafka.md
- content/connectors/sinks/slack.md
- content/connectors/sources/http.md
- content/connectors/sources/mqtt.md
I've tested each of these by manually. We need to automate this in the future.
> Added appropriate versions to connector docs

- content/news/this-week-in-fluvio-0039.md
> Add This week in Fluvio 39

- code/node/package.json
- code/rust/Cargo.lock
- code/rust/Cargo.toml
- code/rust/Dockerfile
- content/news/this-week-in-fluvio-0040.md
In addition to new issue, there is a correction to the release version in TWiF 39
Resolves #343 
Resolves #356 
Resolves #368 
Resolves #369
> Add This week in Fluvio 40

- content/docs/architecture/data-consistency.md
- content/docs/clients/producer.md
- content/news/this-week-in-fluvio-0041.md.tmpl
Added docs and entry to newsletter for Producer Delivery Semantic
Fixed infinyon/fluvio#2481
> Add Delivery Semantics docs

- content/docs/architecture/data-consistency.md
- content/docs/clients/producer.md
- content/news/this-week-in-fluvio-0041.md.tmpl
> Add Delivery Semantics docs (#371)

- content/news/this-week-in-fluvio-0000.md.tmpl
- content/news/this-week-in-fluvio-0041.md
> feat: This week in Fluvio 41

- content/news/this-week-in-fluvio-0041.md
- content/news/this-week-in-fluvio-0042.md
> Add This week in Fluvio 42

- content/news/this-week-in-fluvio-0043.md
The webinar video will be for next week
> This week in Fluvio 43

- content/news/this-week-in-fluvio-0045.md
Announcing the deprecation of fluvio connectors
> Add This Week in Fluvio 45

- content/news/this-week-in-fluvio-0045.md
* Add This Week in Fluvio 45
Announcing the deprecation of fluvio connectors
* Get the CLI command right
Playing with some of the phasing
* Missing word. Minor formatting
> Add This Week in Fluvio 45 (#387)

- embeds/connectors/inbound/http.md
- embeds/connectors/inbound/kafka.md
- embeds/connectors/inbound/mqtt.md
- embeds/connectors/outbound/http.md
- embeds/connectors/outbound/sql.md
Updated docs of released connectors
> update connectors docs

- .github/workflows/htmltest.yml
- .github/workflows/screenshots.yml
- bors.toml
- embeds/download-cli/curl-bash-copy.md
We don't need the beta links anymore
This PR removes bors and is replaced by GH's merge queue.
> ci: Fix download link

- content/_globals.md
- content/cli/client/update.md
- content/docs/_index.md
- content/docs/kubernetes/install.md
- content/docs/switch.md
- content/docs/tutorials/_index.md
- content/docs/update.md
- content/download/_index.md
Fill in missing gaps in docs section, and other changes from previous feedback
> docs: cleanup

- content/connectors/cdk/list-log.md
> fix: list-log section

- content/connectors/cdk/list-log.md
> fix: list-log samples

- content/connectors/cdk/build-test.md
- content/connectors/cdk/generate.md
- content/connectors/cdk/install.md
- content/connectors/cdk/list-log.md
- content/connectors/cdk/publish.md
- content/connectors/cdk/start-shutdown.md
- embeds/client-examples/python/Dockerfile
> fix: log-and-list navigation

- content/connectors/cdk/build-test.md
- content/connectors/cdk/generate.md
- content/connectors/cdk/install.md
- content/connectors/cdk/list-log.md
- content/connectors/cdk/publish.md
- content/connectors/cdk/start-shutdown.md
- embeds/client-examples/python/Dockerfile
* fix: log-and-list navigation
fix log nav consistency
* embeds/client-examples, use python 3.11 (fixes python client example ci step)
> fix: log-and-list navigation (#751)

- Cargo.toml
- embeds/client-examples/rust/Cargo.lock
- embeds/client-examples/rust/Cargo.toml
- embeds/client-examples/rust/Dockerfile
> chore: ci, fix rust example automation

- .github/workflows/pr_labeler.yml
labeler 5 changes format of labeling file signifcantly
> ci: revert to labeler4

- .github/workflows/s;ync-master-to-stable.yml
- scripts/sync-master-to-stable.sh
- Add sync pr script
- add sync pr workflow
> add: stable merge script and test workflow

- .github/workflows/sync-master-to-stable.yml
have to merge then test due to gh action workflow impl
> fix: stable merge workflow

- .github/workflows/sync-master-to-stable.yml
- content/docs/kubernetes/rancher.md
script run 2024-02-15-10.34 ./scripts/sync-master-to-stable.sh
> merge master to stable 2024-02-15-10.34

- embeds/connectors/inbound/http.md
script run 2024-02-27-16.19 ./scripts/sync-master-to-stable.sh
> merge master to stable 2024-02-27-16.19

- content/connectors/cdk/overview.md
from https://github.com/infinyon/mqtt-connector/issues/74
> add: cdk requirements notes

- content/cli/cluster/consumer.md
- content/connectors/connector-config.md
- content/docs/concepts/producer-consumer.md
- data/cli-commands.yml
- embeds/cli/help/fluvio-consume.md
- embeds/cli/help/fluvio-consumer-delete.md
- embeds/cli/help/fluvio-consumer-list.md
- embeds/templates/connector-template-meta-sink-filled.yaml
- embeds/templates/connector-template.yaml
* added consumer offsets docs
* added connectors config and example
> added consumer offsets docs (#829)

- .github/workflows/check_examples.yml
- Cargo.lock
- content/smartmodules/smdk/publish.md
- embeds/client-examples/java/fluvio-java/app/build.gradle
- embeds/client-examples/rust/Cargo.lock
- embeds/client-examples/rust/Cargo.toml
- embeds/client-examples/rust/Dockerfile
- embeds/client-examples/rust/src/main.rs
- **added consumer offsets docs (#829) (#832)**
- **chore: update client-examples workflow (#834)**
- **It is now required to include `smartmodule` (#833)**
- **chore: rust update deps (#835)**
> chore: update from master c7eb8391
